owner: xmlans
repo: apistatus

secrets:
  - AI_API_KEY

sites:
  - name: Official MiniMax API
    slug: minimax-m3
    url: https://api.xmyun.org/v1/chat/completions
    method: POST
    headers:
      - "Authorization: Bearer $AI_API_KEY"
      - "Content-Type: application/json"
    body: >
      {
        "model": "MiniMax-M3",
        "messages": [
          {
            "role": "user",
            "content": "Reply only OK"
          }
        ],
        "max_tokens": 5,
        "stream": false
      }
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"choices"'
    maxResponseTime: 20000

  - name: Official DeepSeek API
    slug: model-2
    url: https://api.xmyun.org/v1/chat/completions
    method: POST
    headers:
      - "Authorization: Bearer $AI_API_KEY"
      - "Content-Type: application/json"
    body: >
      {
        "model": "deepseek-ai/DeepSeek-V4-Flash",
        "messages": [
          {
            "role": "user",
            "content": "Reply only OK"
          }
        ],
        "max_tokens": 5,
        "stream": false
      }
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"choices"'
    maxResponseTime: 20000

  - name: Third Party Minimax
    slug: model-3
    url: https://api.xmyun.org/v1/chat/completions
    method: POST
    headers:
      - "Authorization: Bearer $AI_API_KEY"
      - "Content-Type: application/json"
    body: >
      {
        "model": "MiniMax-M2.7",
        "messages": [
          {
            "role": "user",
            "content": "Reply only OK"
          }
        ],
        "max_tokens": 5,
        "stream": false
      }
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"choices"'
    maxResponseTime: 20000

status-website:
  baseUrl: /apistatus

  name: Star Dream AI Status
  introTitle: "**Star Dream AI** 服务状态"
  introMessage: 在此可查看 API 可用性

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
